In [5]:
import numpy as np
import pandas as pd

from sklearn.model_selection import KFold, cross_val_score
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler, OrdinalEncoder
from sklearn.compose import ColumnTransformer
from sklearn.svm import SVR

from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error

from sklearn.decomposition import PCA

from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import (
    RandomForestRegressor,
    ExtraTreesRegressor,
    GradientBoostingRegressor,
    AdaBoostRegressor
)

from sklearn.neural_network import MLPRegressor

# from xgboost import XGBRegressor

In [6]:
df = pd.read_csv('gurgaon_properties_post_feature_selection_v2.csv')

In [7]:
df.head()

,property_type,sector,price,bedRoom,bathroom,balcony,agePossession,built_up_area,servant room,store room,furnishing_type,luxury_category,floor_category
0,flat,sector 36,0.82,3.0,2.0,2,New Property,850.0,0.0,0.0,0.0,Low,Low Floor
1,flat,sector 89,0.95,2.0,2.0,2,New Property,1226.0,1.0,0.0,0.0,Low,Mid Floor
2,flat,sohna road,0.32,2.0,2.0,1,New Property,1000.0,0.0,0.0,0.0,Low,High Floor
3,flat,sector 92,1.60,3.0,4.0,3+,Relatively New,1615.0,1.0,0.0,1.0,High,Mid Floor
4,flat,sector 102,0.48,2.0,2.0,1,Relatively New,582.0,0.0,1.0,0.0,High,Mid Floor

In [1]:
# import sys
# print(sys.executable)

C:\Users\USER\anaconda3\envs\data_env_old\python.exe

In [12]:
# import sys, pandas as pd, numpy as np
# print(sys.executable)
# print(pd.__version__)
# print(np.__version__)

C:\Users\USER\Desktop\UDEMY\Capstone1 Project ML\venv\Scripts\python.exe
2.3.3
2.2.6

In [8]:
# import pickle

# with open('df.pkl', 'wb') as file:
#     pickle.dump(df, file)

In [9]:
df['furnishing_type'].value_counts()

furnishing_type
0.0    2349
1.0    1018
2.0     187
Name: count, dtype: int64

In [10]:
# 0 -> unfurnished
# 1 -> semifurnished
# 2 -> furnished
df['furnishing_type'] = df['furnishing_type'].replace({0.0:'unfurnished',1.0:'semifurnished',2.0:'furnished'})

In [11]:
df.head()

,property_type,sector,price,bedRoom,bathroom,balcony,agePossession,built_up_area,servant room,store room,furnishing_type,luxury_category,floor_category
0,flat,sector 36,0.82,3.0,2.0,2,New Property,850.0,0.0,0.0,unfurnished,Low,Low Floor
1,flat,sector 89,0.95,2.0,2.0,2,New Property,1226.0,1.0,0.0,unfurnished,Low,Mid Floor
2,flat,sohna road,0.32,2.0,2.0,1,New Property,1000.0,0.0,0.0,unfurnished,Low,High Floor
3,flat,sector 92,1.60,3.0,4.0,3+,Relatively New,1615.0,1.0,0.0,semifurnished,High,Mid Floor
4,flat,sector 102,0.48,2.0,2.0,1,Relatively New,582.0,0.0,1.0,unfurnished,High,Mid Floor

In [7]:
X = df.drop(columns=['price'])
y = df['price']

In [8]:
# The price col is right skewed to normalize we use log1p

# We do training on logspace and prediction of its exponent

# Applying the log1p transformation to the target variable
y_transformed = np.log1p(y)

### Ordinal Encoding

In [9]:
columns_to_encode = ['property_type','sector', 'balcony', 'agePossession', 'furnishing_type', 'luxury_category', 'floor_category']

In [10]:
# Creating a column transformer for preprocessing
preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), ['bedRoom', 'bathroom', 'built_up_area', 'servant room', 'store room']),
        ('cat', OrdinalEncoder(), columns_to_encode)
    ], 
    remainder='passthrough'
)

In [11]:
# Creating a pipeline
pipeline = Pipeline([
    ('preprocessor', preprocessor),
    ('regressor', LinearRegression())
])

In [12]:
# K-fold cross-validation
kfold = KFold(n_splits=10, shuffle=True, random_state=42)
scores = cross_val_score(pipeline, X, y_transformed, cv=kfold, scoring='r2')

In [13]:
scores.mean(),scores.std()

(0.7363096633436828, 0.03238005754429932)

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X,y_transformed,test_size=0.2,random_state=42)

In [15]:
pipeline.fit(X_train,y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('num', StandardScaler(),
                                                  ['bedRoom', 'bathroom',
                                                   'built_up_area',
                                                   'servant room',
                                                   'store room']),
                                                 ('cat', OrdinalEncoder(),
                                                  ['property_type', 'sector',
                                                   'balcony', 'agePossession',
                                                   'furnishing_type',
                                                   'luxury_category',
                                                   'floor_category'])])),
                ('regressor', LinearRegression())])

In [16]:
y_pred = pipeline.predict(X_test)

In [17]:
y_pred = np.expm1(y_pred)

In [18]:
mean_absolute_error(np.expm1(y_test),y_pred)

# On an avg we are making an error of 94%

0.946382216008936

In [19]:
# model_name >> model name string
# model = actual model object

def scorer(model_name, model):
    
    output = []
    
    output.append(model_name)
    
    pipeline = Pipeline([
        ('preprocessor', preprocessor),
        ('regressor', model)
    ])
    
    # K-fold cross-validation
    kfold = KFold(n_splits=10, shuffle=True, random_state=42)
    scores = cross_val_score(pipeline, X, y_transformed, cv=kfold, scoring='r2')
    
    output.append(scores.mean())
    
    X_train, X_test, y_train, y_test = train_test_split(X,y_transformed,test_size=0.2,random_state=42)
    
    pipeline.fit(X_train,y_train)
    
    y_pred = pipeline.predict(X_test)
    
    y_pred = np.expm1(y_pred)
    
    output.append(mean_absolute_error(np.expm1(y_test),y_pred))
    
    return output

In [20]:
model_dict = {
    'linear_reg':LinearRegression(),
    'svr':SVR(),
    'ridge':Ridge(),
    'LASSO':Lasso(),
    'decision tree': DecisionTreeRegressor(),
    'random forest':RandomForestRegressor(),
    'extra trees': ExtraTreesRegressor(),
    'gradient boosting': GradientBoostingRegressor(),
    'adaboost': AdaBoostRegressor(),
    'mlp': MLPRegressor(),
    'xgboost':XGBRegressor()
}

In [21]:
model_output = []
for model_name,model in model_dict.items():
    model_output.append(scorer(model_name, model))

C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\model_selection\_validation.py:978: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\metrics\_scorer.py", line 140, in __call__
    score = scorer._score(
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\metrics\_scorer.py", line 380, in _score
    y_pred = method_caller(
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\metrics\_scorer.py", line 90, in _cached_call
    result, _ = _get_response_values(
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\utils\_response.py", line 242, in _get_response_values
    y_pred, pos_label = prediction_method(X), None
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\pipeline.py", line 788, in predict
    return self.steps[-1][1].predict(Xt, **params)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\contextlib.py", line 126, in __exit__
    next(self.gen)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\pipeline.py", line 60, in _raise_or_warn_if_not_fitted
    check_is_fitted(estimator)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\utils\validation.py", line 1756, in check_is_fitted
    if not _is_fitted(estimator, attributes, all_or_any):
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\utils\validation.py", line 1665, in _is_fitted
    return estimator.__sklearn_is_fitted__()
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\pipeline.py", line 1321, in __sklearn_is_fitted__
    check_is_fitted(last_step)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\utils\validation.py", line 1751, in check_is_fitted
    tags = get_tags(estimator)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\utils\_tags.py", line 430, in get_tags
    sklearn_tags_provider[klass] = klass.__sklearn_tags__(estimator)  # type: ignore[attr-defined]
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\base.py", line 613, in __sklearn_tags__
    tags = super().__sklearn_tags__()
AttributeError: 'super' object has no attribute '__sklearn_tags__'

  warnings.warn(
C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\model_selection\_validation.py:978: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\metrics\_scorer.py", line 140, in __call__
    score = scorer._score(
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\metrics\_scorer.py", line 380, in _score
    y_pred = method_caller(
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\metrics\_scorer.py", line 90, in _cached_call
    result, _ = _get_response_values(
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\utils\_response.py", line 242, in _get_response_values
    y_pred, pos_label = prediction_method(X), None
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\pipeline.py", line 788, in predict
    return self.steps[-1][1].predict(Xt, **params)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\contextlib.py", line 126, in __exit__
    next(self.gen)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\pipeline.py", line 60, in _raise_or_warn_if_not_fitted
    check_is_fitted(estimator)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\utils\validation.py", line 1756, in check_is_fitted
    if not _is_fitted(estimator, attributes, all_or_any):
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\utils\validation.py", line 1665, in _is_fitted
    return estimator.__sklearn_is_fitted__()
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\pipeline.py", line 1321, in __sklearn_is_fitted__
    check_is_fitted(last_step)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\utils\validation.py", line 1751, in check_is_fitted
    tags = get_tags(estimator)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\utils\_tags.py", line 430, in get_tags
    sklearn_tags_provider[klass] = klass.__sklearn_tags__(estimator)  # type: ignore[attr-defined]
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\base.py", line 613, in __sklearn_tags__
    tags = super().__sklearn_tags__()
AttributeError: 'super' object has no attribute '__sklearn_tags__'

  warnings.warn(
C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\model_selection\_validation.py:978: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\metrics\_scorer.py", line 140, in __call__
    score = scorer._score(
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\metrics\_scorer.py", line 380, in _score
    y_pred = method_caller(
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\metrics\_scorer.py", line 90, in _cached_call
    result, _ = _get_response_values(
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\utils\_response.py", line 242, in _get_response_values
    y_pred, pos_label = prediction_method(X), None
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\pipeline.py", line 788, in predict
    return self.steps[-1][1].predict(Xt, **params)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\contextlib.py", line 126, in __exit__
    next(self.gen)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\pipeline.py", line 60, in _raise_or_warn_if_not_fitted
    check_is_fitted(estimator)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\utils\validation.py", line 1756, in check_is_fitted
    if not _is_fitted(estimator, attributes, all_or_any):
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\utils\validation.py", line 1665, in _is_fitted
    return estimator.__sklearn_is_fitted__()
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\pipeline.py", line 1321, in __sklearn_is_fitted__
    check_is_fitted(last_step)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\utils\validation.py", line 1751, in check_is_fitted
    tags = get_tags(estimator)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\utils\_tags.py", line 430, in get_tags
    sklearn_tags_provider[klass] = klass.__sklearn_tags__(estimator)  # type: ignore[attr-defined]
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\base.py", line 613, in __sklearn_tags__
    tags = super().__sklearn_tags__()
AttributeError: 'super' object has no attribute '__sklearn_tags__'

  warnings.warn(
C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\model_selection\_validation.py:978: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\metrics\_scorer.py", line 140, in __call__
    score = scorer._score(
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\metrics\_scorer.py", line 380, in _score
    y_pred = method_caller(
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\metrics\_scorer.py", line 90, in _cached_call
    result, _ = _get_response_values(
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\utils\_response.py", line 242, in _get_response_values
    y_pred, pos_label = prediction_method(X), None
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\pipeline.py", line 788, in predict
    return self.steps[-1][1].predict(Xt, **params)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\contextlib.py", line 126, in __exit__
    next(self.gen)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\pipeline.py", line 60, in _raise_or_warn_if_not_fitted
    check_is_fitted(estimator)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\utils\validation.py", line 1756, in check_is_fitted
    if not _is_fitted(estimator, attributes, all_or_any):
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\utils\validation.py", line 1665, in _is_fitted
    return estimator.__sklearn_is_fitted__()
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\pipeline.py", line 1321, in __sklearn_is_fitted__
    check_is_fitted(last_step)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\utils\validation.py", line 1751, in check_is_fitted
    tags = get_tags(estimator)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\utils\_tags.py", line 430, in get_tags
    sklearn_tags_provider[klass] = klass.__sklearn_tags__(estimator)  # type: ignore[attr-defined]
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\base.py", line 613, in __sklearn_tags__
    tags = super().__sklearn_tags__()
AttributeError: 'super' object has no attribute '__sklearn_tags__'

  warnings.warn(
C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\model_selection\_validation.py:978: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\metrics\_scorer.py", line 140, in __call__
    score = scorer._score(
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\metrics\_scorer.py", line 380, in _score
    y_pred = method_caller(
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\metrics\_scorer.py", line 90, in _cached_call
    result, _ = _get_response_values(
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\utils\_response.py", line 242, in _get_response_values
    y_pred, pos_label = prediction_method(X), None
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\pipeline.py", line 788, in predict
    return self.steps[-1][1].predict(Xt, **params)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\contextlib.py", line 126, in __exit__
    next(self.gen)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\pipeline.py", line 60, in _raise_or_warn_if_not_fitted
    check_is_fitted(estimator)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\utils\validation.py", line 1756, in check_is_fitted
    if not _is_fitted(estimator, attributes, all_or_any):
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\utils\validation.py", line 1665, in _is_fitted
    return estimator.__sklearn_is_fitted__()
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\pipeline.py", line 1321, in __sklearn_is_fitted__
    check_is_fitted(last_step)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\utils\validation.py", line 1751, in check_is_fitted
    tags = get_tags(estimator)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\utils\_tags.py", line 430, in get_tags
    sklearn_tags_provider[klass] = klass.__sklearn_tags__(estimator)  # type: ignore[attr-defined]
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\base.py", line 613, in __sklearn_tags__
    tags = super().__sklearn_tags__()
AttributeError: 'super' object has no attribute '__sklearn_tags__'

  warnings.warn(
C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\model_selection\_validation.py:978: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\metrics\_scorer.py", line 140, in __call__
    score = scorer._score(
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\metrics\_scorer.py", line 380, in _score
    y_pred = method_caller(
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\metrics\_scorer.py", line 90, in _cached_call
    result, _ = _get_response_values(
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\utils\_response.py", line 242, in _get_response_values
    y_pred, pos_label = prediction_method(X), None
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\pipeline.py", line 788, in predict
    return self.steps[-1][1].predict(Xt, **params)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\contextlib.py", line 126, in __exit__
    next(self.gen)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\pipeline.py", line 60, in _raise_or_warn_if_not_fitted
    check_is_fitted(estimator)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\utils\validation.py", line 1756, in check_is_fitted
    if not _is_fitted(estimator, attributes, all_or_any):
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\utils\validation.py", line 1665, in _is_fitted
    return estimator.__sklearn_is_fitted__()
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\pipeline.py", line 1321, in __sklearn_is_fitted__
    check_is_fitted(last_step)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\utils\validation.py", line 1751, in check_is_fitted
    tags = get_tags(estimator)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\utils\_tags.py", line 430, in get_tags
    sklearn_tags_provider[klass] = klass.__sklearn_tags__(estimator)  # type: ignore[attr-defined]
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\base.py", line 613, in __sklearn_tags__
    tags = super().__sklearn_tags__()
AttributeError: 'super' object has no attribute '__sklearn_tags__'

  warnings.warn(
C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\model_selection\_validation.py:978: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\metrics\_scorer.py", line 140, in __call__
    score = scorer._score(
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\metrics\_scorer.py", line 380, in _score
    y_pred = method_caller(
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\metrics\_scorer.py", line 90, in _cached_call
    result, _ = _get_response_values(
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\utils\_response.py", line 242, in _get_response_values
    y_pred, pos_label = prediction_method(X), None
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\pipeline.py", line 788, in predict
    return self.steps[-1][1].predict(Xt, **params)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\contextlib.py", line 126, in __exit__
    next(self.gen)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\pipeline.py", line 60, in _raise_or_warn_if_not_fitted
    check_is_fitted(estimator)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\utils\validation.py", line 1756, in check_is_fitted
    if not _is_fitted(estimator, attributes, all_or_any):
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\utils\validation.py", line 1665, in _is_fitted
    return estimator.__sklearn_is_fitted__()
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\pipeline.py", line 1321, in __sklearn_is_fitted__
    check_is_fitted(last_step)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\utils\validation.py", line 1751, in check_is_fitted
    tags = get_tags(estimator)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\utils\_tags.py", line 430, in get_tags
    sklearn_tags_provider[klass] = klass.__sklearn_tags__(estimator)  # type: ignore[attr-defined]
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\base.py", line 613, in __sklearn_tags__
    tags = super().__sklearn_tags__()
AttributeError: 'super' object has no attribute '__sklearn_tags__'

  warnings.warn(
C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\model_selection\_validation.py:978: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\metrics\_scorer.py", line 140, in __call__
    score = scorer._score(
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\metrics\_scorer.py", line 380, in _score
    y_pred = method_caller(
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\metrics\_scorer.py", line 90, in _cached_call
    result, _ = _get_response_values(
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\utils\_response.py", line 242, in _get_response_values
    y_pred, pos_label = prediction_method(X), None
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\pipeline.py", line 788, in predict
    return self.steps[-1][1].predict(Xt, **params)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\contextlib.py", line 126, in __exit__
    next(self.gen)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\pipeline.py", line 60, in _raise_or_warn_if_not_fitted
    check_is_fitted(estimator)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\utils\validation.py", line 1756, in check_is_fitted
    if not _is_fitted(estimator, attributes, all_or_any):
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\utils\validation.py", line 1665, in _is_fitted
    return estimator.__sklearn_is_fitted__()
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\pipeline.py", line 1321, in __sklearn_is_fitted__
    check_is_fitted(last_step)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\utils\validation.py", line 1751, in check_is_fitted
    tags = get_tags(estimator)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\utils\_tags.py", line 430, in get_tags
    sklearn_tags_provider[klass] = klass.__sklearn_tags__(estimator)  # type: ignore[attr-defined]
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\base.py", line 613, in __sklearn_tags__
    tags = super().__sklearn_tags__()
AttributeError: 'super' object has no attribute '__sklearn_tags__'

  warnings.warn(

AttributeError: 'super' object has no attribute '__sklearn_tags__'

In [22]:
model_df = pd.DataFrame(model_output, columns=['name','r2','mae'])

In [23]:
model_df.sort_values(['mae'])

                name        r2       mae
5      random forest  0.880661  0.534100
6        extra trees  0.867353  0.555253
7  gradient boosting  0.872647  0.576677
9                mlp  0.808277  0.685885
4      decision tree  0.773987  0.741059
8           adaboost  0.755610  0.781086
1                svr  0.764201  0.847264
2              ridge  0.736313  0.946339
0         linear_reg  0.736310  0.946382
3              LASSO  0.059434  1.528906

### OneHotEncoding

In [24]:
# Creating a column transformer for preprocessing
preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), ['bedRoom', 'bathroom', 'built_up_area', 'servant room', 'store room']),
        ('cat', OrdinalEncoder(), columns_to_encode),
        ('cat1',OneHotEncoder(drop='first',sparse_output=False),['sector','agePossession'])
    ], 
    remainder='passthrough'
)

In [25]:
# Creating a pipeline
pipeline = Pipeline([
    ('preprocessor', preprocessor),
    
    ('regressor', LinearRegression())
])

In [26]:
# K-fold cross-validation
kfold = KFold(n_splits=10, shuffle=True, random_state=42)
scores = cross_val_score(pipeline, X, y_transformed, cv=kfold, scoring='r2')

In [27]:
scores.mean()

# after applying OHE score.mean get improved to 0.85 from 0.73

0.854732932359442

In [28]:
scores.std()

0.01597275515613503

In [29]:
X_train, X_test, y_train, y_test = train_test_split(X,y_transformed,test_size=0.2,random_state=42)

In [30]:
pipeline.fit(X_train,y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('num', StandardScaler(),
                                                  ['bedRoom', 'bathroom',
                                                   'built_up_area',
                                                   'servant room',
                                                   'store room']),
                                                 ('cat', OrdinalEncoder(),
                                                  ['property_type', 'sector',
                                                   'balcony', 'agePossession',
                                                   'furnishing_type',
                                                   'luxury_category',
                                                   'floor_category']),
                                                 ('cat1',
                                                  OneHotEncoder(drop='first',
                                                                sparse_output=False),
                                                  ['sector',
                                                   'agePossession'])])),
                ('regressor', LinearRegression())])

In [31]:
y_pred = pipeline.predict(X_test)

In [32]:
y_pred = np.expm1(y_pred)

In [33]:
mean_absolute_error(np.expm1(y_test),y_pred)

# mean absolute error also reduced from 0.94 to 0.64

0.6491718597838264

In [34]:
def scorer(model_name, model):
    
    output = []
    
    output.append(model_name)
    
    pipeline = Pipeline([
        ('preprocessor', preprocessor),
        ('regressor', model)
    ])
    
    # K-fold cross-validation
    kfold = KFold(n_splits=10, shuffle=True, random_state=42)
    scores = cross_val_score(pipeline, X, y_transformed, cv=kfold, scoring='r2')
    
    output.append(scores.mean())
    
    X_train, X_test, y_train, y_test = train_test_split(X,y_transformed,test_size=0.2,random_state=42)
    
    pipeline.fit(X_train,y_train)
    
    y_pred = pipeline.predict(X_test)
    
    y_pred = np.expm1(y_pred)
    
    output.append(mean_absolute_error(np.expm1(y_test),y_pred))
    
    return output

In [35]:
model_dict = {
    'linear_reg':LinearRegression(),
    'svr':SVR(),
    'ridge':Ridge(),
    'LASSO':Lasso(),
    'decision tree': DecisionTreeRegressor(),
    'random forest':RandomForestRegressor(),
    'extra trees': ExtraTreesRegressor(),
    'gradient boosting': GradientBoostingRegressor(),
    'adaboost': AdaBoostRegressor(),
    'mlp': MLPRegressor(),
    'xgboost':XGBRegressor()
}

In [36]:
model_output = []
for model_name,model in model_dict.items():
    model_output.append(scorer(model_name, model))

C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\model_selection\_validation.py:978: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\metrics\_scorer.py", line 140, in __call__
    score = scorer._score(
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\metrics\_scorer.py", line 380, in _score
    y_pred = method_caller(
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\metrics\_scorer.py", line 90, in _cached_call
    result, _ = _get_response_values(
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\utils\_response.py", line 242, in _get_response_values
    y_pred, pos_label = prediction_method(X), None
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\pipeline.py", line 788, in predict
    return self.steps[-1][1].predict(Xt, **params)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\contextlib.py", line 126, in __exit__
    next(self.gen)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\pipeline.py", line 60, in _raise_or_warn_if_not_fitted
    check_is_fitted(estimator)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\utils\validation.py", line 1756, in check_is_fitted
    if not _is_fitted(estimator, attributes, all_or_any):
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\utils\validation.py", line 1665, in _is_fitted
    return estimator.__sklearn_is_fitted__()
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\pipeline.py", line 1321, in __sklearn_is_fitted__
    check_is_fitted(last_step)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\utils\validation.py", line 1751, in check_is_fitted
    tags = get_tags(estimator)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\utils\_tags.py", line 430, in get_tags
    sklearn_tags_provider[klass] = klass.__sklearn_tags__(estimator)  # type: ignore[attr-defined]
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\base.py", line 613, in __sklearn_tags__
    tags = super().__sklearn_tags__()
AttributeError: 'super' object has no attribute '__sklearn_tags__'

  warnings.warn(
C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\model_selection\_validation.py:978: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\metrics\_scorer.py", line 140, in __call__
    score = scorer._score(
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\metrics\_scorer.py", line 380, in _score
    y_pred = method_caller(
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\metrics\_scorer.py", line 90, in _cached_call
    result, _ = _get_response_values(
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\utils\_response.py", line 242, in _get_response_values
    y_pred, pos_label = prediction_method(X), None
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\pipeline.py", line 788, in predict
    return self.steps[-1][1].predict(Xt, **params)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\contextlib.py", line 126, in __exit__
    next(self.gen)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\pipeline.py", line 60, in _raise_or_warn_if_not_fitted
    check_is_fitted(estimator)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\utils\validation.py", line 1756, in check_is_fitted
    if not _is_fitted(estimator, attributes, all_or_any):
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\utils\validation.py", line 1665, in _is_fitted
    return estimator.__sklearn_is_fitted__()
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\pipeline.py", line 1321, in __sklearn_is_fitted__
    check_is_fitted(last_step)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\utils\validation.py", line 1751, in check_is_fitted
    tags = get_tags(estimator)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\utils\_tags.py", line 430, in get_tags
    sklearn_tags_provider[klass] = klass.__sklearn_tags__(estimator)  # type: ignore[attr-defined]
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\base.py", line 613, in __sklearn_tags__
    tags = super().__sklearn_tags__()
AttributeError: 'super' object has no attribute '__sklearn_tags__'

  warnings.warn(
C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\model_selection\_validation.py:978: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\metrics\_scorer.py", line 140, in __call__
    score = scorer._score(
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\metrics\_scorer.py", line 380, in _score
    y_pred = method_caller(
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\metrics\_scorer.py", line 90, in _cached_call
    result, _ = _get_response_values(
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\utils\_response.py", line 242, in _get_response_values
    y_pred, pos_label = prediction_method(X), None
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\pipeline.py", line 788, in predict
    return self.steps[-1][1].predict(Xt, **params)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\contextlib.py", line 126, in __exit__
    next(self.gen)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\pipeline.py", line 60, in _raise_or_warn_if_not_fitted
    check_is_fitted(estimator)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\utils\validation.py", line 1756, in check_is_fitted
    if not _is_fitted(estimator, attributes, all_or_any):
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\utils\validation.py", line 1665, in _is_fitted
    return estimator.__sklearn_is_fitted__()
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\pipeline.py", line 1321, in __sklearn_is_fitted__
    check_is_fitted(last_step)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\utils\validation.py", line 1751, in check_is_fitted
    tags = get_tags(estimator)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\utils\_tags.py", line 430, in get_tags
    sklearn_tags_provider[klass] = klass.__sklearn_tags__(estimator)  # type: ignore[attr-defined]
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\base.py", line 613, in __sklearn_tags__
    tags = super().__sklearn_tags__()
AttributeError: 'super' object has no attribute '__sklearn_tags__'

  warnings.warn(
C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\model_selection\_validation.py:978: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\metrics\_scorer.py", line 140, in __call__
    score = scorer._score(
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\metrics\_scorer.py", line 380, in _score
    y_pred = method_caller(
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\metrics\_scorer.py", line 90, in _cached_call
    result, _ = _get_response_values(
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\utils\_response.py", line 242, in _get_response_values
    y_pred, pos_label = prediction_method(X), None
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\pipeline.py", line 788, in predict
    return self.steps[-1][1].predict(Xt, **params)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\contextlib.py", line 126, in __exit__
    next(self.gen)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\pipeline.py", line 60, in _raise_or_warn_if_not_fitted
    check_is_fitted(estimator)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\utils\validation.py", line 1756, in check_is_fitted
    if not _is_fitted(estimator, attributes, all_or_any):
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\utils\validation.py", line 1665, in _is_fitted
    return estimator.__sklearn_is_fitted__()
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\pipeline.py", line 1321, in __sklearn_is_fitted__
    check_is_fitted(last_step)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\utils\validation.py", line 1751, in check_is_fitted
    tags = get_tags(estimator)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\utils\_tags.py", line 430, in get_tags
    sklearn_tags_provider[klass] = klass.__sklearn_tags__(estimator)  # type: ignore[attr-defined]
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\base.py", line 613, in __sklearn_tags__
    tags = super().__sklearn_tags__()
AttributeError: 'super' object has no attribute '__sklearn_tags__'

  warnings.warn(
C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\model_selection\_validation.py:978: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\metrics\_scorer.py", line 140, in __call__
    score = scorer._score(
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\metrics\_scorer.py", line 380, in _score
    y_pred = method_caller(
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\metrics\_scorer.py", line 90, in _cached_call
    result, _ = _get_response_values(
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\utils\_response.py", line 242, in _get_response_values
    y_pred, pos_label = prediction_method(X), None
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\pipeline.py", line 788, in predict
    return self.steps[-1][1].predict(Xt, **params)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\contextlib.py", line 126, in __exit__
    next(self.gen)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\pipeline.py", line 60, in _raise_or_warn_if_not_fitted
    check_is_fitted(estimator)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\utils\validation.py", line 1756, in check_is_fitted
    if not _is_fitted(estimator, attributes, all_or_any):
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\utils\validation.py", line 1665, in _is_fitted
    return estimator.__sklearn_is_fitted__()
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\pipeline.py", line 1321, in __sklearn_is_fitted__
    check_is_fitted(last_step)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\utils\validation.py", line 1751, in check_is_fitted
    tags = get_tags(estimator)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\utils\_tags.py", line 430, in get_tags
    sklearn_tags_provider[klass] = klass.__sklearn_tags__(estimator)  # type: ignore[attr-defined]
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\base.py", line 613, in __sklearn_tags__
    tags = super().__sklearn_tags__()
AttributeError: 'super' object has no attribute '__sklearn_tags__'

  warnings.warn(
C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\model_selection\_validation.py:978: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\metrics\_scorer.py", line 140, in __call__
    score = scorer._score(
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\metrics\_scorer.py", line 380, in _score
    y_pred = method_caller(
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\metrics\_scorer.py", line 90, in _cached_call
    result, _ = _get_response_values(
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\utils\_response.py", line 242, in _get_response_values
    y_pred, pos_label = prediction_method(X), None
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\pipeline.py", line 788, in predict
    return self.steps[-1][1].predict(Xt, **params)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\contextlib.py", line 126, in __exit__
    next(self.gen)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\pipeline.py", line 60, in _raise_or_warn_if_not_fitted
    check_is_fitted(estimator)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\utils\validation.py", line 1756, in check_is_fitted
    if not _is_fitted(estimator, attributes, all_or_any):
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\utils\validation.py", line 1665, in _is_fitted
    return estimator.__sklearn_is_fitted__()
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\pipeline.py", line 1321, in __sklearn_is_fitted__
    check_is_fitted(last_step)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\utils\validation.py", line 1751, in check_is_fitted
    tags = get_tags(estimator)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\utils\_tags.py", line 430, in get_tags
    sklearn_tags_provider[klass] = klass.__sklearn_tags__(estimator)  # type: ignore[attr-defined]
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\base.py", line 613, in __sklearn_tags__
    tags = super().__sklearn_tags__()
AttributeError: 'super' object has no attribute '__sklearn_tags__'

  warnings.warn(
C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\model_selection\_validation.py:978: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\metrics\_scorer.py", line 140, in __call__
    score = scorer._score(
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\metrics\_scorer.py", line 380, in _score
    y_pred = method_caller(
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\metrics\_scorer.py", line 90, in _cached_call
    result, _ = _get_response_values(
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\utils\_response.py", line 242, in _get_response_values
    y_pred, pos_label = prediction_method(X), None
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\pipeline.py", line 788, in predict
    return self.steps[-1][1].predict(Xt, **params)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\contextlib.py", line 126, in __exit__
    next(self.gen)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\pipeline.py", line 60, in _raise_or_warn_if_not_fitted
    check_is_fitted(estimator)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\utils\validation.py", line 1756, in check_is_fitted
    if not _is_fitted(estimator, attributes, all_or_any):
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\utils\validation.py", line 1665, in _is_fitted
    return estimator.__sklearn_is_fitted__()
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\pipeline.py", line 1321, in __sklearn_is_fitted__
    check_is_fitted(last_step)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\utils\validation.py", line 1751, in check_is_fitted
    tags = get_tags(estimator)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\utils\_tags.py", line 430, in get_tags
    sklearn_tags_provider[klass] = klass.__sklearn_tags__(estimator)  # type: ignore[attr-defined]
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\base.py", line 613, in __sklearn_tags__
    tags = super().__sklearn_tags__()
AttributeError: 'super' object has no attribute '__sklearn_tags__'

  warnings.warn(
C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\model_selection\_validation.py:978: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\metrics\_scorer.py", line 140, in __call__
    score = scorer._score(
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\metrics\_scorer.py", line 380, in _score
    y_pred = method_caller(
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\metrics\_scorer.py", line 90, in _cached_call
    result, _ = _get_response_values(
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\utils\_response.py", line 242, in _get_response_values
    y_pred, pos_label = prediction_method(X), None
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\pipeline.py", line 788, in predict
    return self.steps[-1][1].predict(Xt, **params)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\contextlib.py", line 126, in __exit__
    next(self.gen)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\pipeline.py", line 60, in _raise_or_warn_if_not_fitted
    check_is_fitted(estimator)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\utils\validation.py", line 1756, in check_is_fitted
    if not _is_fitted(estimator, attributes, all_or_any):
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\utils\validation.py", line 1665, in _is_fitted
    return estimator.__sklearn_is_fitted__()
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\pipeline.py", line 1321, in __sklearn_is_fitted__
    check_is_fitted(last_step)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\utils\validation.py", line 1751, in check_is_fitted
    tags = get_tags(estimator)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\utils\_tags.py", line 430, in get_tags
    sklearn_tags_provider[klass] = klass.__sklearn_tags__(estimator)  # type: ignore[attr-defined]
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\base.py", line 613, in __sklearn_tags__
    tags = super().__sklearn_tags__()
AttributeError: 'super' object has no attribute '__sklearn_tags__'

  warnings.warn(
C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\model_selection\_validation.py:978: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\metrics\_scorer.py", line 140, in __call__
    score = scorer._score(

AttributeError: 'super' object has no attribute '__sklearn_tags__'

In [37]:
model_df = pd.DataFrame(model_output, columns=['name','r2','mae'])

In [38]:
model_df.sort_values(['mae'])

                name        r2       mae
6        extra trees  0.895330  0.459969
5      random forest  0.891433  0.502484
7  gradient boosting  0.876586  0.569087
9                mlp  0.874039  0.583664
0         linear_reg  0.854733  0.649172
2              ridge  0.854984  0.653066
4      decision tree  0.805337  0.685968
1                svr  0.769781  0.835053
8           adaboost  0.749735  0.839057
3              LASSO  0.059434  1.528906

### OneHotEncoding With PCA

In [39]:
# Creating a column transformer for preprocessing
preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), ['bedRoom', 'bathroom', 'built_up_area', 'servant room', 'store room']),
        ('cat', OrdinalEncoder(), columns_to_encode),
        ('cat1',OneHotEncoder(drop='first',sparse_output=False),['sector','agePossession'])
    ], 
    remainder='passthrough'
)

In [40]:
# Creating a pipeline
pipeline = Pipeline([
    ('preprocessor', preprocessor),
    ('pca', PCA(n_components=0.95)),
    ('regressor', LinearRegression())
])

In [41]:
# K-fold cross-validation
kfold = KFold(n_splits=10, shuffle=True, random_state=42)
scores = cross_val_score(pipeline, X, y_transformed, cv=kfold, scoring='r2')

In [42]:
scores.mean()

0.062252014314511384

In [43]:
scores.std()

0.01986059407164016

In [44]:
def scorer(model_name, model):
    
    output = []
    
    output.append(model_name)
    
    pipeline = Pipeline([
        ('preprocessor', preprocessor),
        ('pca', PCA(n_components=0.95)),
        ('regressor', model)
    ])
    
    # K-fold cross-validation
    kfold = KFold(n_splits=10, shuffle=True, random_state=42)
    scores = cross_val_score(pipeline, X, y_transformed, cv=kfold, scoring='r2')
    
    output.append(scores.mean())
    
    X_train, X_test, y_train, y_test = train_test_split(X,y_transformed,test_size=0.2,random_state=42)
    
    pipeline.fit(X_train,y_train)
    
    y_pred = pipeline.predict(X_test)
    
    y_pred = np.expm1(y_pred)
    
    output.append(mean_absolute_error(np.expm1(y_test),y_pred))
    
    return output

In [45]:
model_dict = {
    'linear_reg':LinearRegression(),
    'svr':SVR(),
    'ridge':Ridge(),
    'LASSO':Lasso(),
    'decision tree': DecisionTreeRegressor(),
    'random forest':RandomForestRegressor(),
    'extra trees': ExtraTreesRegressor(),
    'gradient boosting': GradientBoostingRegressor(),
    'adaboost': AdaBoostRegressor(),
    'mlp': MLPRegressor(),
    'xgboost':XGBRegressor()
}

In [46]:
model_output = []
for model_name,model in model_dict.items():
    model_output.append(scorer(model_name, model))

C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\model_selection\_validation.py:978: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\metrics\_scorer.py", line 140, in __call__
    score = scorer._score(
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\metrics\_scorer.py", line 380, in _score
    y_pred = method_caller(
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\metrics\_scorer.py", line 90, in _cached_call
    result, _ = _get_response_values(
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\utils\_response.py", line 242, in _get_response_values
    y_pred, pos_label = prediction_method(X), None
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\pipeline.py", line 788, in predict
    return self.steps[-1][1].predict(Xt, **params)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\contextlib.py", line 126, in __exit__
    next(self.gen)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\pipeline.py", line 60, in _raise_or_warn_if_not_fitted
    check_is_fitted(estimator)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\utils\validation.py", line 1756, in check_is_fitted
    if not _is_fitted(estimator, attributes, all_or_any):
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\utils\validation.py", line 1665, in _is_fitted
    return estimator.__sklearn_is_fitted__()
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\pipeline.py", line 1321, in __sklearn_is_fitted__
    check_is_fitted(last_step)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\utils\validation.py", line 1751, in check_is_fitted
    tags = get_tags(estimator)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\utils\_tags.py", line 430, in get_tags
    sklearn_tags_provider[klass] = klass.__sklearn_tags__(estimator)  # type: ignore[attr-defined]
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\base.py", line 613, in __sklearn_tags__
    tags = super().__sklearn_tags__()
AttributeError: 'super' object has no attribute '__sklearn_tags__'

  warnings.warn(
C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\model_selection\_validation.py:978: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\metrics\_scorer.py", line 140, in __call__
    score = scorer._score(
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\metrics\_scorer.py", line 380, in _score
    y_pred = method_caller(
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\metrics\_scorer.py", line 90, in _cached_call
    result, _ = _get_response_values(
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\utils\_response.py", line 242, in _get_response_values
    y_pred, pos_label = prediction_method(X), None
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\pipeline.py", line 788, in predict
    return self.steps[-1][1].predict(Xt, **params)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\contextlib.py", line 126, in __exit__
    next(self.gen)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\pipeline.py", line 60, in _raise_or_warn_if_not_fitted
    check_is_fitted(estimator)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\utils\validation.py", line 1756, in check_is_fitted
    if not _is_fitted(estimator, attributes, all_or_any):
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\utils\validation.py", line 1665, in _is_fitted
    return estimator.__sklearn_is_fitted__()
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\pipeline.py", line 1321, in __sklearn_is_fitted__
    check_is_fitted(last_step)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\utils\validation.py", line 1751, in check_is_fitted
    tags = get_tags(estimator)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\utils\_tags.py", line 430, in get_tags
    sklearn_tags_provider[klass] = klass.__sklearn_tags__(estimator)  # type: ignore[attr-defined]
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\base.py", line 613, in __sklearn_tags__
    tags = super().__sklearn_tags__()
AttributeError: 'super' object has no attribute '__sklearn_tags__'

  warnings.warn(
C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\model_selection\_validation.py:978: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\metrics\_scorer.py", line 140, in __call__
    score = scorer._score(
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\metrics\_scorer.py", line 380, in _score
    y_pred = method_caller(
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\metrics\_scorer.py", line 90, in _cached_call
    result, _ = _get_response_values(
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\utils\_response.py", line 242, in _get_response_values
    y_pred, pos_label = prediction_method(X), None
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\pipeline.py", line 788, in predict
    return self.steps[-1][1].predict(Xt, **params)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\contextlib.py", line 126, in __exit__
    next(self.gen)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\pipeline.py", line 60, in _raise_or_warn_if_not_fitted
    check_is_fitted(estimator)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\utils\validation.py", line 1756, in check_is_fitted
    if not _is_fitted(estimator, attributes, all_or_any):
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\utils\validation.py", line 1665, in _is_fitted
    return estimator.__sklearn_is_fitted__()
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\pipeline.py", line 1321, in __sklearn_is_fitted__
    check_is_fitted(last_step)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\utils\validation.py", line 1751, in check_is_fitted
    tags = get_tags(estimator)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\utils\_tags.py", line 430, in get_tags
    sklearn_tags_provider[klass] = klass.__sklearn_tags__(estimator)  # type: ignore[attr-defined]
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\base.py", line 613, in __sklearn_tags__
    tags = super().__sklearn_tags__()
AttributeError: 'super' object has no attribute '__sklearn_tags__'

  warnings.warn(
C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\model_selection\_validation.py:978: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\metrics\_scorer.py", line 140, in __call__
    score = scorer._score(
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\metrics\_scorer.py", line 380, in _score
    y_pred = method_caller(
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\metrics\_scorer.py", line 90, in _cached_call
    result, _ = _get_response_values(
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\utils\_response.py", line 242, in _get_response_values
    y_pred, pos_label = prediction_method(X), None
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\pipeline.py", line 788, in predict
    return self.steps[-1][1].predict(Xt, **params)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\contextlib.py", line 126, in __exit__
    next(self.gen)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\pipeline.py", line 60, in _raise_or_warn_if_not_fitted
    check_is_fitted(estimator)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\utils\validation.py", line 1756, in check_is_fitted
    if not _is_fitted(estimator, attributes, all_or_any):
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\utils\validation.py", line 1665, in _is_fitted
    return estimator.__sklearn_is_fitted__()
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\pipeline.py", line 1321, in __sklearn_is_fitted__
    check_is_fitted(last_step)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\utils\validation.py", line 1751, in check_is_fitted
    tags = get_tags(estimator)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\utils\_tags.py", line 430, in get_tags
    sklearn_tags_provider[klass] = klass.__sklearn_tags__(estimator)  # type: ignore[attr-defined]
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\base.py", line 613, in __sklearn_tags__
    tags = super().__sklearn_tags__()
AttributeError: 'super' object has no attribute '__sklearn_tags__'

  warnings.warn(
C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\model_selection\_validation.py:978: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\metrics\_scorer.py", line 140, in __call__
    score = scorer._score(
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\metrics\_scorer.py", line 380, in _score
    y_pred = method_caller(
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\metrics\_scorer.py", line 90, in _cached_call
    result, _ = _get_response_values(
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\utils\_response.py", line 242, in _get_response_values
    y_pred, pos_label = prediction_method(X), None
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\pipeline.py", line 788, in predict
    return self.steps[-1][1].predict(Xt, **params)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\contextlib.py", line 126, in __exit__
    next(self.gen)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\pipeline.py", line 60, in _raise_or_warn_if_not_fitted
    check_is_fitted(estimator)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\utils\validation.py", line 1756, in check_is_fitted
    if not _is_fitted(estimator, attributes, all_or_any):
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\utils\validation.py", line 1665, in _is_fitted
    return estimator.__sklearn_is_fitted__()
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\pipeline.py", line 1321, in __sklearn_is_fitted__
    check_is_fitted(last_step)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\utils\validation.py", line 1751, in check_is_fitted
    tags = get_tags(estimator)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\utils\_tags.py", line 430, in get_tags
    sklearn_tags_provider[klass] = klass.__sklearn_tags__(estimator)  # type: ignore[attr-defined]
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\base.py", line 613, in __sklearn_tags__
    tags = super().__sklearn_tags__()
AttributeError: 'super' object has no attribute '__sklearn_tags__'

  warnings.warn(
C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\model_selection\_validation.py:978: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\metrics\_scorer.py", line 140, in __call__
    score = scorer._score(
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\metrics\_scorer.py", line 380, in _score
    y_pred = method_caller(
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\metrics\_scorer.py", line 90, in _cached_call
    result, _ = _get_response_values(
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\utils\_response.py", line 242, in _get_response_values
    y_pred, pos_label = prediction_method(X), None
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\pipeline.py", line 788, in predict
    return self.steps[-1][1].predict(Xt, **params)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\contextlib.py", line 126, in __exit__
    next(self.gen)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\pipeline.py", line 60, in _raise_or_warn_if_not_fitted
    check_is_fitted(estimator)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\utils\validation.py", line 1756, in check_is_fitted
    if not _is_fitted(estimator, attributes, all_or_any):
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\utils\validation.py", line 1665, in _is_fitted
    return estimator.__sklearn_is_fitted__()
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\pipeline.py", line 1321, in __sklearn_is_fitted__
    check_is_fitted(last_step)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\utils\validation.py", line 1751, in check_is_fitted
    tags = get_tags(estimator)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\utils\_tags.py", line 430, in get_tags
    sklearn_tags_provider[klass] = klass.__sklearn_tags__(estimator)  # type: ignore[attr-defined]
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\base.py", line 613, in __sklearn_tags__
    tags = super().__sklearn_tags__()
AttributeError: 'super' object has no attribute '__sklearn_tags__'

  warnings.warn(
C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\model_selection\_validation.py:978: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\metrics\_scorer.py", line 140, in __call__
    score = scorer._score(
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\metrics\_scorer.py", line 380, in _score
    y_pred = method_caller(
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\metrics\_scorer.py", line 90, in _cached_call
    result, _ = _get_response_values(
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\utils\_response.py", line 242, in _get_response_values
    y_pred, pos_label = prediction_method(X), None
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\pipeline.py", line 788, in predict
    return self.steps[-1][1].predict(Xt, **params)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\contextlib.py", line 126, in __exit__
    next(self.gen)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\pipeline.py", line 60, in _raise_or_warn_if_not_fitted
    check_is_fitted(estimator)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\utils\validation.py", line 1756, in check_is_fitted
    if not _is_fitted(estimator, attributes, all_or_any):
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\utils\validation.py", line 1665, in _is_fitted
    return estimator.__sklearn_is_fitted__()
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\pipeline.py", line 1321, in __sklearn_is_fitted__
    check_is_fitted(last_step)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\utils\validation.py", line 1751, in check_is_fitted
    tags = get_tags(estimator)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\utils\_tags.py", line 430, in get_tags
    sklearn_tags_provider[klass] = klass.__sklearn_tags__(estimator)  # type: ignore[attr-defined]
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\base.py", line 613, in __sklearn_tags__
    tags = super().__sklearn_tags__()
AttributeError: 'super' object has no attribute '__sklearn_tags__'

  warnings.warn(
C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\model_selection\_validation.py:978: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\metrics\_scorer.py", line 140, in __call__
    score = scorer._score(
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\metrics\_scorer.py", line 380, in _score
    y_pred = method_caller(
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\metrics\_scorer.py", line 90, in _cached_call
    result, _ = _get_response_values(
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\utils\_response.py", line 242, in _get_response_values
    y_pred, pos_label = prediction_method(X), None
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\pipeline.py", line 788, in predict
    return self.steps[-1][1].predict(Xt, **params)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\contextlib.py", line 126, in __exit__
    next(self.gen)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\pipeline.py", line 60, in _raise_or_warn_if_not_fitted
    check_is_fitted(estimator)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\utils\validation.py", line 1756, in check_is_fitted
    if not _is_fitted(estimator, attributes, all_or_any):
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\utils\validation.py", line 1665, in _is_fitted
    return estimator.__sklearn_is_fitted__()
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\pipeline.py", line 1321, in __sklearn_is_fitted__
    check_is_fitted(last_step)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\utils\validation.py", line 1751, in check_is_fitted
    tags = get_tags(estimator)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\utils\_tags.py", line 430, in get_tags
    sklearn_tags_provider[klass] = klass.__sklearn_tags__(estimator)  # type: ignore[attr-defined]
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\base.py", line 613, in __sklearn_tags__
    tags = super().__sklearn_tags__()
AttributeError: 'super' object has no attribute '__sklearn_tags__'

  warnings.warn(
C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\model_selection\_validation.py:978: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\metrics\_scorer.py", line 140, in __call__
    score = scorer._score(

AttributeError: 'super' object has no attribute '__sklearn_tags__'

In [47]:
model_df = pd.DataFrame(model_output, columns=['name','r2','mae'])

In [48]:
model_df.sort_values(['mae'])

                name        r2       mae
5      random forest  0.762481  0.655114
6        extra trees  0.739431  0.698971
4      decision tree  0.696442  0.761509
7  gradient boosting  0.610623  0.987906
1                svr  0.218073  1.361163
8           adaboost  0.300335  1.367888
9                mlp  0.201114  1.438131
2              ridge  0.062252  1.526707
0         linear_reg  0.062252  1.526707
3              LASSO  0.059676  1.528739

### Target Encoder

In [49]:
import category_encoders as ce

In [50]:
columns_to_encode = ['property_type','sector', 'balcony', 'agePossession', 'furnishing_type', 'luxury_category', 'floor_category']

# Creating a column transformer for preprocessing
preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), ['bedRoom', 'bathroom', 'built_up_area', 'servant room', 'store room']),
        ('cat', OrdinalEncoder(), columns_to_encode),
        ('cat1',OneHotEncoder(drop='first',sparse_output=False),['agePossession']),
        ('target_enc', ce.TargetEncoder(), ['sector'])
    ], 
    remainder='passthrough'
)

In [51]:
# Creating a pipeline
pipeline = Pipeline([
    ('preprocessor', preprocessor),
    ('regressor', LinearRegression())
])

In [52]:
# K-fold cross-validation
kfold = KFold(n_splits=10, shuffle=True, random_state=42)
scores = cross_val_score(pipeline, X, y_transformed, cv=kfold, scoring='r2', error_score='raise')

AttributeError: 'super' object has no attribute '__sklearn_tags__'

In [53]:
scores.mean(),scores.std()

(0.062252014314511384, 0.01986059407164016)

In [54]:
def scorer(model_name, model):
    
    output = []
    
    output.append(model_name)
    
    pipeline = Pipeline([
        ('preprocessor', preprocessor),
        ('regressor', model)
    ])
    
    # K-fold cross-validation
    kfold = KFold(n_splits=10, shuffle=True, random_state=42)
    scores = cross_val_score(pipeline, X, y_transformed, cv=kfold, scoring='r2')
    
    output.append(scores.mean())
    
    X_train, X_test, y_train, y_test = train_test_split(X,y_transformed,test_size=0.2,random_state=42)
    
    pipeline.fit(X_train,y_train)
    
    y_pred = pipeline.predict(X_test)
    
    y_pred = np.expm1(y_pred)
    
    output.append(mean_absolute_error(np.expm1(y_test),y_pred))
    
    return output

In [55]:
model_dict = {
    'linear_reg':LinearRegression(),
    'svr':SVR(),
    'ridge':Ridge(),
    'LASSO':Lasso(),
    'decision tree': DecisionTreeRegressor(),
    'random forest':RandomForestRegressor(),
    'extra trees': ExtraTreesRegressor(),
    'gradient boosting': GradientBoostingRegressor(),
    'adaboost': AdaBoostRegressor(),
    'mlp': MLPRegressor(),
    'xgboost':XGBRegressor()
}

In [56]:
model_output = []
for model_name,model in model_dict.items():
    model_output.append(scorer(model_name, model))

ValueError:
All the 10 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
10 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\model_selection\_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\pipeline.py", line 654, in fit
    Xt = self._fit(X, y, routed_params, raw_params=params)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\pipeline.py", line 588, in _fit
    X, fitted_transformer = fit_transform_one_cached(
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\joblib\memory.py", line 326, in __call__
    return self.func(*args, **kwargs)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\pipeline.py", line 1551, in _fit_transform_one
    res = transformer.fit_transform(X, y, **params.get("fit_transform", {}))
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\utils\_set_output.py", line 319, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\compose\_column_transformer.py", line 1001, in fit_transform
    result = self._call_func_on_transformers(
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\compose\_column_transformer.py", line 910, in _call_func_on_transformers
    return Parallel(n_jobs=self.n_jobs)(jobs)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\utils\parallel.py", line 77, in __call__
    return super().__call__(iterable_with_config)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\joblib\parallel.py", line 1986, in __call__
    return output if self.return_generator else list(output)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\joblib\parallel.py", line 1914, in _get_sequential_output
    res = func(*args, **kwargs)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\utils\parallel.py", line 139, in __call__
    return self.function(*args, **kwargs)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\pipeline.py", line 1551, in _fit_transform_one
    res = transformer.fit_transform(X, y, **params.get("fit_transform", {}))
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\utils\_set_output.py", line 319, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\category_encoders\utils.py", line 474, in fit_transform
    return self.fit(X, y, **fit_params).transform(X, y)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\category_encoders\utils.py", line 299, in fit
    self._check_fit_inputs(X, y)
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\category_encoders\utils.py", line 336, in _check_fit_inputs
    if self._get_tags().get('supervised_encoder'):
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\base.py", line 417, in _get_tags
    return _to_old_tags(get_tags(self))
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\utils\_tags.py", line 430, in get_tags
    sklearn_tags_provider[klass] = klass.__sklearn_tags__(estimator)  # type: ignore[attr-defined]
  File "C:\Users\USER\anaconda3\envs\data_env_old\lib\site-packages\sklearn\base.py", line 859, in __sklearn_tags__
    tags = super().__sklearn_tags__()
AttributeError: 'super' object has no attribute '__sklearn_tags__'

In [57]:
model_df = pd.DataFrame(model_output, columns=['name','r2','mae'])

In [58]:
model_df.sort_values(['mae'])

Empty DataFrame
Columns: [name, r2, mae]
Index: []

### Hyperparameter Tuning

In [59]:
from sklearn.model_selection import GridSearchCV

In [64]:
param_grid = {
    'regressor__n_estimators': [50, 100, 200, 300],
    'regressor__max_depth': [None, 10, 20, 30],
    'regressor__max_samples':[0.1, 0.25, 0.5, 1.0],
    'regressor__max_features': ['auto', 'sqrt']
}

In [60]:
columns_to_encode = ['property_type','sector', 'balcony', 'agePossession', 'furnishing_type', 'luxury_category', 'floor_category']

# Creating a column transformer for preprocessing
preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), ['bedRoom', 'bathroom', 'built_up_area', 'servant room', 'store room']),
        ('cat', OrdinalEncoder(), columns_to_encode),
        ('cat1',OneHotEncoder(drop='first',sparse_output=False),['agePossession']),
        ('target_enc', ce.TargetEncoder(), ['sector'])
    ], 
    remainder='passthrough'
)

In [61]:
pipeline = Pipeline([
    ('preprocessor', preprocessor),
    ('regressor', RandomForestRegressor())
])

In [62]:
kfold = KFold(n_splits=10, shuffle=True, random_state=42)

In [65]:
search = GridSearchCV(pipeline, param_grid, cv=kfold, scoring='r2', n_jobs=-1, verbose=4, error_score='raise')

In [66]:
search.fit(X, y_transformed)

Fitting 10 folds for each of 128 candidates, totalling 1280 fits

AttributeError: 'super' object has no attribute '__sklearn_tags__'

In [68]:
# final_pipe = search.best_estimator_

In [70]:
# search.best_params_

In [ ]:
# search.best_score_

In [72]:
# final_pipe.fit(X,y_transformed)

### Exporting the model

In [73]:
preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), ['bedRoom', 'bathroom', 'built_up_area', 'servant room', 'store room']),
        ('cat', OrdinalEncoder(), columns_to_encode),
        ('cat1',OneHotEncoder(drop='first',sparse_output=False),['sector','agePossession'])
    ], 
    remainder='passthrough'
)

In [74]:
pipeline = Pipeline([
    ('preprocessor', preprocessor),
    ('regressor', RandomForestRegressor(n_estimators=500))
])

In [75]:
pipeline.fit(X,y_transformed)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('num', StandardScaler(),
                                                  ['bedRoom', 'bathroom',
                                                   'built_up_area',
                                                   'servant room',
                                                   'store room']),
                                                 ('cat', OrdinalEncoder(),
                                                  ['property_type', 'sector',
                                                   'balcony', 'agePossession',
                                                   'furnishing_type',
                                                   'luxury_category',
                                                   'floor_category']),
                                                 ('cat1',
                                                  OneHotEncoder(drop='first',
                                                                sparse_output=False),
                                                  ['sector',
                                                   'agePossession'])])),
                ('regressor', RandomForestRegressor(n_estimators=500))])

In [76]:
import pickle

with open('pipeline.pkl', 'wb') as file:
    pickle.dump(pipeline, file)

### Trying out the predictions

In [77]:
X.columns

Index(['property_type', 'sector', 'bedRoom', 'bathroom', 'balcony',
       'agePossession', 'built_up_area', 'servant room', 'store room',
       'furnishing_type', 'luxury_category', 'floor_category'],
      dtype='object')

In [79]:
X.iloc[0].values

array(['flat', 'sector 36', 3.0, 2.0, '2', 'New Property', 850.0, 0.0,
       0.0, 'unfurnished', 'Low', 'Low Floor'], dtype=object)

In [80]:
data = [['house', 'sector 102', 4, 3, '3+', 'New Property', 2750, 0, 0, 'unfurnished', 'Low', 'Low Floor']]
columns = ['property_type', 'sector', 'bedRoom', 'bathroom', 'balcony',
       'agePossession', 'built_up_area', 'servant room', 'store room',
       'furnishing_type', 'luxury_category', 'floor_category']

In [81]:
# Convert to DataFrame
one_df = pd.DataFrame(data, columns=columns)

one_df

,property_type,sector,bedRoom,bathroom,balcony,agePossession,built_up_area,servant room,store room,furnishing_type,luxury_category,floor_category
0,house,sector 102,4,3,3+,New Property,2750,0,0,unfurnished,Low,Low Floor

In [82]:
np.expm1(pipeline.predict(one_df))

array([3.05951608])

In [83]:
X.dtypes

property_type       object
sector              object
bedRoom            float64
bathroom           float64
balcony             object
agePossession       object
built_up_area      float64
servant room       float64
store room         float64
furnishing_type     object
luxury_category     object
floor_category      object
dtype: object

In [84]:
X['sector'].unique()

array(['sector 36', 'sector 89', 'sohna road', 'sector 92', 'sector 102',
       'gwal pahari', 'sector 108', 'sector 105', 'sector 26',
       'sector 109', 'sector 28', 'sector 65', 'sector 12', 'sector 85',
       'sector 70a', 'sector 30', 'sector 107', 'sector 3', 'sector 2',
       'sector 41', 'sector 4', 'sector 62', 'sector 49', 'sector 81',
       'sector 66', 'sector 86', 'sector 48', 'sector 51', 'sector 37',
       'sector 111', 'sector 67', 'sector 113', 'sector 13', 'sector 61',
       'sector 69', 'sector 67a', 'sector 37d', 'sector 82', 'sector 53',
       'sector 74', 'sector 52', 'sector 43', 'sector 14', 'sector 25',
       'sector 95', 'sector 56', 'sector 83', 'sector 104', 'sector 88a',
       'sector 55', 'sector 50', 'sector 84', 'sector 91', 'sector 76',
       'sector 82a', 'sector 78', 'manesar', 'sector 93', 'sector 7',
       'sector 71', 'sector 110', 'sector 33', 'sector 70', 'sector 103',
       'sector 90', 'sector 38', 'sector 79', 'sector 112', 'sector 22',
       'sector 59', 'sector 99', 'sector 9', 'sector 58', 'sector 77',
       'sector 1', 'sector 57', 'sector 106', 'dwarka expressway',
       'sector 63', 'sector 5', 'sector 40', 'sector 23', 'sector 6',
       'sector 72', 'sector 47', 'sector 45', 'sector 68', 'sector 11',
       'sector 60', 'sector 39', 'sector 63a', 'sector 24', 'sector 46',
       'sector 17', 'sector 15', 'sector 10', 'sector 31', 'sector 21',
       'sector 80', 'sector 73', 'sector 54', 'sector 8', 'sector 88',
       'sector 27'], dtype=object)

In [85]:
sorted(X['sector'].unique().tolist())

['dwarka expressway',
 'gwal pahari',
 'manesar',
 'sector 1',
 'sector 10',
 'sector 102',
 'sector 103',
 'sector 104',
 'sector 105',
 'sector 106',
 'sector 107',
 'sector 108',
 'sector 109',
 'sector 11',
 'sector 110',
 'sector 111',
 'sector 112',
 'sector 113',
 'sector 12',
 'sector 13',
 'sector 14',
 'sector 15',
 'sector 17',
 'sector 2',
 'sector 21',
 'sector 22',
 'sector 23',
 'sector 24',
 'sector 25',
 'sector 26',
 'sector 27',
 'sector 28',
 'sector 3',
 'sector 30',
 'sector 31',
 'sector 33',
 'sector 36',
 'sector 37',
 'sector 37d',
 'sector 38',
 'sector 39',
 'sector 4',
 'sector 40',
 'sector 41',
 'sector 43',
 'sector 45',
 'sector 46',
 'sector 47',
 'sector 48',
 'sector 49',
 'sector 5',
 'sector 50',
 'sector 51',
 'sector 52',
 'sector 53',
 'sector 54',
 'sector 55',
 'sector 56',
 'sector 57',
 'sector 58',
 'sector 59',
 'sector 6',
 'sector 60',
 'sector 61',
 'sector 62',
 'sector 63',
 'sector 63a',
 'sector 65',
 'sector 66',
 'sector 67',
 'sector 67a',
 'sector 68',
 'sector 69',
 'sector 7',
 'sector 70',
 'sector 70a',
 'sector 71',
 'sector 72',
 'sector 73',
 'sector 74',
 'sector 76',
 'sector 77',
 'sector 78',
 'sector 79',
 'sector 8',
 'sector 80',
 'sector 81',
 'sector 82',
 'sector 82a',
 'sector 83',
 'sector 84',
 'sector 85',
 'sector 86',
 'sector 88',
 'sector 88a',
 'sector 89',
 'sector 9',
 'sector 90',
 'sector 91',
 'sector 92',
 'sector 93',
 'sector 95',
 'sector 99',
 'sohna road']